//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stephanie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stephanie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DeviceInfo&gt;
        ///  &lt;RequestCommands&gt;
        ///    &lt;Request1 RequestPacketType=&quot;Stephanie.RequestPacket.DataRequestPacket&quot; RequestCommandText=&quot;GET1&quot; /&gt;
        ///    &lt;Request2 RequestPacketType=&quot;Stephanie.RequestPacket.AlarmRequestPacket&quot; RequestCommandText=&quot;GET2&quot; /&gt;
        ///    &lt;Request3 RequestPacketType=&quot;Stephanie.RequestPacket.SettingsRequestPacket&quot; RequestCommandText=&quot;GET3&quot; /&gt;
        ///	&lt;Request4 RequestPacketType=&quot;Stephanie.RequestPacket.DeviceSettingsRequestPacket&quot; RequestCommandText=&quot;GET4&quot; /&gt;
        ///  &lt;/RequestCommands&gt;
        ///  &lt;Paramaters&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid alarm number received from device (received : {0}).
        /// </summary>
        internal static string ERR_ALARM_NO {
            get {
                return ResourceManager.GetString("ERR_ALARM_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid alarm priority received from device (received : {0}).
        /// </summary>
        internal static string ERR_ALARM_PRIORITY {
            get {
                return ResourceManager.GetString("ERR_ALARM_PRIORITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms priority info list XML resource is not valid.
        /// </summary>
        internal static string ERR_ALARM_PRIORITY_XML {
            get {
                return ResourceManager.GetString("ERR_ALARM_PRIORITY_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarms info list XML resource is not valid.
        /// </summary>
        internal static string ERR_ALARM_XML {
            get {
                return ResourceManager.GetString("ERR_ALARM_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bed ID is invalid or not set.
        /// </summary>
        internal static string ERR_BEDID {
            get {
                return ResourceManager.GetString("ERR_BEDID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet CheckSum error.
        /// </summary>
        internal static string ERR_CHKSUM {
            get {
                return ResourceManager.GetString("ERR_CHKSUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Error.
        /// </summary>
        internal static string ERR_COMM_ERROR {
            get {
                return ResourceManager.GetString("ERR_COMM_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Failed.
        /// </summary>
        internal static string ERR_CONN_FAILED {
            get {
                return ResourceManager.GetString("ERR_CONN_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data received from device.
        /// </summary>
        internal static string ERR_INVALID_DATA {
            get {
                return ResourceManager.GetString("ERR_INVALID_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message ID received from device (received : {0}).
        /// </summary>
        internal static string ERR_MESSAGE_ID {
            get {
                return ResourceManager.GetString("ERR_MESSAGE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message length received from device (Expected: {0} , Received: {1}).
        /// </summary>
        internal static string ERR_MESSAGE_LENGTH {
            get {
                return ResourceManager.GetString("ERR_MESSAGE_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Parameter arrived from the device (Paramter ID : {0}).
        /// </summary>
        internal static string ERR_PARAMETER_ID {
            get {
                return ResourceManager.GetString("ERR_PARAMETER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter info list XML resource is not valid.
        /// </summary>
        internal static string ERR_PARAMINFOLIST_XML {
            get {
                return ResourceManager.GetString("ERR_PARAMINFOLIST_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestCommands XML resource is not valid (missing Type or RequestCommandText).
        /// </summary>
        internal static string ERR_REQUESTCOMMANDS_XML {
            get {
                return ResourceManager.GetString("ERR_REQUESTCOMMANDS_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Packet type retrieved from RequestCommands XML could not be found in the assembly.
        /// </summary>
        internal static string ERR_REQUESTPACKET_TYPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_REQUESTPACKET_TYPE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication Timeout.
        /// </summary>
        internal static string ERR_TIMEOUT {
            get {
                return ResourceManager.GetString("ERR_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized packet type (packet type : &quot;{0}&quot;).
        /// </summary>
        internal static string ERR_UNRECOGNIZED_PACKETTYPE {
            get {
                return ResourceManager.GetString("ERR_UNRECOGNIZED_PACKETTYPE", resourceCulture);
            }
        }
    }
}
